# This file was generated by GoReleaser. DO NOT EDIT.
cask "depdog" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "92a878729663d6751aab556fdc0a416d7893e4a74b50664cb6186ad485af423c"
      url "https://github.com/matterpale/depdog/releases/download/v#{version}/depdog_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "9267f68f263bfb2be072c4bc8272965497b54875047b802ad0d8df4d411f61f0"
      url "https://github.com/matterpale/depdog/releases/download/v#{version}/depdog_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "fa2502834901a2b7c6f5bc4c8f3052c34ede0a4790d20b2d2ed8df714b9910ff"
      url "https://github.com/matterpale/depdog/releases/download/v#{version}/depdog_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "a749b2640d5795386a58d7a4c78ee6907fc4723dce7ebbbb71fdbdc2f47fa522"
      url "https://github.com/matterpale/depdog/releases/download/v#{version}/depdog_#{version}_linux_arm64.tar.gz"
    end
  end

  name "depdog"
  desc "A Dependency Watchdog"
  homepage "https://github.com/matterpale/depdog"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "depdog"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/depdog"]
    end
  end

  # No zap stanza required

end
