# This file was generated by GoReleaser. DO NOT EDIT.
cask "depdog" do
  version "0.6.0"

  on_macos do
    on_intel do
      sha256 "5bc261fd1571296a5c02ed3e7aafe54202c8fa5baa555336583918e6bac79a2d"
      url "https://github.com/matterpale/depdog/releases/download/v#{version}/depdog_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "a35dc0f5a7ccec6085db93ffe09fbf48dbde9f40dd89e723c2b3a60706c64bc4"
      url "https://github.com/matterpale/depdog/releases/download/v#{version}/depdog_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "5a7fae52569817ea2a1d82b58a15d565c9bd82b8ea968733061a1f8c20034156"
      url "https://github.com/matterpale/depdog/releases/download/v#{version}/depdog_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "32122ed4a1ee47403ce526c95c27ce9223b0a98f8241ad3b4c813bf4c0535d35"
      url "https://github.com/matterpale/depdog/releases/download/v#{version}/depdog_#{version}_linux_arm64.tar.gz"
    end
  end

  name "depdog"
  desc "A Dependency Watchdog"
  homepage "https://github.com/matterpale/depdog"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "depdog"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/depdog"]
    end
  end

  # No zap stanza required

end
