# This file was generated by GoReleaser. DO NOT EDIT.
cask "depdog" do
  version "0.3.1"

  on_macos do
    on_intel do
      sha256 "2aaab34735a1b3286ff3c6b70483e94bda3ce60de72624a2cf30a2956e1220bc"
      url "https://github.com/matterpale/depdog/releases/download/v#{version}/depdog_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "c7811800f84e58fc3b9987c10acf80c62b5007ae6120f3e9354916177f50eb89"
      url "https://github.com/matterpale/depdog/releases/download/v#{version}/depdog_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "92cbccc8045b0e5f2b8340cde0bafae90bc70e533fad23b58307ba9b69b797ef"
      url "https://github.com/matterpale/depdog/releases/download/v#{version}/depdog_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "be29aae40c4a35ad443a16a1f0dd87dc69d71929fefd39a70295bb013872cf7b"
      url "https://github.com/matterpale/depdog/releases/download/v#{version}/depdog_#{version}_linux_arm64.tar.gz"
    end
  end

  name "depdog"
  desc "A Dependency Watchdog"
  homepage "https://github.com/matterpale/depdog"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "depdog"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/depdog"]
    end
  end

  # No zap stanza required

end
